### PR TITLE
Add optional parameter for overflow menu and fixed menu overflow issue

### LINKED ISSUE #2: [Adaptive Navigation] Menu icon is not center aligned with navigation rail items
Currently:
Screen Shot 2020-08-11 at 1 36 29 PM

Should be more like:
Screen Shot 2020-08-11 at 1 37 17 PM

### LINKED ISSUE #3: [Adaptive Navigation] Create flag for repeating destinations in menu.
Currently, the overflow menu defaults to include overflow destinations _and_ the original destinations. There should be a flag to exclude the original destinations that are already available in the bottom navigation bar or the navigation rail.

A switch should also be added to the examples to show this behavior.

### LINKED ISSUE #332: [Adaptive Navigation] Create flag for repeating destinations in menu.

### PR DESCRIPTION
**Pull request by JoseAlba**
Closes material-foundation/flutter-packages#332

### CODE REVIEW

**Review by rami-a — COMMENTED** [review]
I don't think this PR is actually addressing https://github.com/material-components/material-components-flutter-adaptive/issues/2 or is that why the width of the rail is being set to 56?

**Comment by rami-a** [comment]
From looking at the screenshots in https://github.com/material-components/material-components-flutter-adaptive/issues/2, I think the drawer menu icon position is the issue, not the nav rail width.

File: adaptive_navigation/example/lib/custom_scaffold.dart [hunk 1]
```diff
@@ -27,6 +29,8 @@ class _CustomScaffoldDemoState extends State<CustomScaffoldDemo> {
           return NavigationType.bottom;
         }
       },
+      fabInRail: _fabInRail,
+      overflowDestinationAddedToMenu: _overflowDestinationAddedToMenu,
```
Comment (clocksmith) [inline adaptive_navigation/example/lib/custom_scaffold.dart]: The overflow destinations are always added to menu, so this should be something like "includeBaseDestinationsInMenu"

File: adaptive_navigation/lib/scaffold.dart [hunk 2]
```diff
@@ -221,9 +232,15 @@ class AdaptiveNavigationScaffold extends StatelessWidget {
...
-        destinations.sublist(0, math.min(destinations.length, 7));
-    final drawerDestinations = destinations.length > 7 ? destinations : [];
+    final int railDestinationsOverflow = 7;
+    final railDestinations = destinations.sublist(
+      0,
+      math.min(destinations.length, railDestinationsOverflow),
+    );
+    final drawerDestinations = destinations.length > railDestinationsOverflow
+        ? destinations.sublist(
+            overflowDestinationAddedToMenu ? railDestinationsOverflow : 0)
```
Comment (clocksmith) [inline adaptive_navigation/lib/scaffold.dart]: This would be inverted with new flag name, which should default to true

File: adaptive_navigation/lib/scaffold.dart [hunk 3]
```diff
@@ -233,6 +250,7 @@ class AdaptiveNavigationScaffold extends StatelessWidget {
         children: [
           NavigationRail(
             leading: fabInRail ? floatingActionButton : null,
+            minWidth: 56,
```
Comment (clocksmith) [inline adaptive_navigation/lib/scaffold.dart]: This should stay 72, but position of menu for nav rail state should be shifted to center align

File: adaptive_navigation/lib/scaffold.dart [hunk 4]
```diff
@@ -312,7 +330,8 @@ class AdaptiveNavigationScaffold extends StatelessWidget {
     return Row(
       children: [
         Drawer(
-          child: Column(
+          child: ListView(
```
Comment (clocksmith) [inline adaptive_navigation/lib/scaffold.dart]: This might be OK but maybe should be a separate PR since it's not related to these issues

Does this give the overscroll interaction (bounce on iOS, bubble on Android...) even if it does not scroll?

File: adaptive_navigation/lib/scaffold.dart (hunk 2 above)
Comment (JoseAlba) [reply adaptive_navigation/lib/scaffold.dart]: Done

File: adaptive_navigation/example/lib/custom_scaffold.dart (hunk 1 above)
Comment (JoseAlba) [reply adaptive_navigation/example/lib/custom_scaffold.dart]: Done

File: adaptive_navigation/lib/scaffold.dart (hunk 4 above)
Comment (JoseAlba) [reply adaptive_navigation/lib/scaffold.dart]: Done

File: adaptive_navigation/lib/scaffold.dart (hunk 3 above)
Comment (JoseAlba) [reply adaptive_navigation/lib/scaffold.dart]: The position of the Menu is not controlled by the nav rail but instead by the Drawer. If there is a drawer it will show up. 

The adaptive nav rail has no control on what type of AppBar the user choses and because of this we don't access to the menu button. Instead of modiying the menu button I modified the width of the navigation rail.

**Comment by JoseAlba** [comment]
> From looking at the screenshots in material-foundation/flutter-packages#320, I think the drawer menu icon position is the issue, not the nav rail width.

 The position of the Menu is not controlled by the nav rail but instead by the Drawer. If there is a drawer it will show up.

The adaptive nav rail has no control over what type of AppBar the user chooses and because of this, we don't access the menu button. Instead of modifying the menu button, I modified the width of the navigation rail.

File: adaptive_navigation/example/lib/custom_scaffold.dart [hunk 5]
```diff
@@ -8,6 +8,8 @@ class CustomScaffoldDemo extends StatefulWidget {
 
 class _CustomScaffoldDemoState extends State<CustomScaffoldDemo> {
   int _destinationCount = 5;
+  bool _fabInRail = false;
+  bool _overflowDestinationAddedToMenu = true;
```
Comment (rami-a) [inline adaptive_navigation/example/lib/custom_scaffold.dart]: Rename to `_includeBaseDestinationInMenu` to match the rail

File: adaptive_navigation/example/lib/default_scaffold.dart [hunk 6]
```diff
@@ -9,6 +13,7 @@ class DefaultScaffoldDemo extends StatefulWidget {
 class _DefaultScaffoldDemoState extends State<DefaultScaffoldDemo> {
   int _destinationCount = 5;
   bool _fabInRail = false;
+  bool _overflowDestinationAddedToMenu = true;
```
Comment (rami-a) [inline adaptive_navigation/example/lib/default_scaffold.dart]: Rename to `_includeBaseDestinationInMenu` to match the rail

File: adaptive_navigation/lib/scaffold.dart (hunk 3 above)
Comment (rami-a) [reply adaptive_navigation/lib/scaffold.dart]: I think the nav rail default width of 72 should remain.

One option could be to customize the 2 examples so that the menu button is inset more to align with the rail? Not sure if there's a good solution to this out-of-the-box

**Review by rami-a — APPROVED** [review]

File: adaptive_navigation/lib/scaffold.dart [hunk 7]
```diff
@@ -164,6 +165,10 @@ class AdaptiveNavigationScaffold extends StatelessWidget {
   /// [floatingActionButtonAnimation] are ignored.
   final bool fabInRail;
 
+  /// Weather the overflow menu defaults to include overflow destinations and
+  /// the overflow destinations.
+  final bool includeBaseDestinationInMenu;
```
Comment (clocksmith) [inline adaptive_navigation/lib/scaffold.dart]: nit: includeBaseDestinationsInMenu

File: adaptive_navigation/lib/scaffold.dart (hunk 3 above)
Comment (clocksmith) [reply adaptive_navigation/lib/scaffold.dart]: It is OK if this PR closes #3 and not #2. #2 might be more tricky since there may be no simple way to control the inset of the menu without modifying the API

File: adaptive_navigation/example/lib/default_scaffold.dart (hunk 6 above)
Comment (JoseAlba) [reply adaptive_navigation/example/lib/default_scaffold.dart]: Done

File: adaptive_navigation/lib/scaffold.dart (hunk 7 above)
Comment (JoseAlba) [reply adaptive_navigation/lib/scaffold.dart]: Done

File: adaptive_navigation/example/lib/custom_scaffold.dart (hunk 5 above)
Comment (JoseAlba) [reply adaptive_navigation/example/lib/custom_scaffold.dart]: DOne

File: adaptive_navigation/lib/scaffold.dart (hunk 3 above)
Comment (JoseAlba) [reply adaptive_navigation/lib/scaffold.dart]: Updated PR description so it only closes PR 3

**Review by clocksmith — APPROVED** [review]
